//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlexaSkillEntities : DbContext
    {
        public AlexaSkillEntities()
            : base("name=AlexaSkillEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<CoreTemperature> CoreTemperatures { get; set; }
        public virtual DbSet<Meat> Meats { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ExitMessage> ExitMessages { get; set; }
        public virtual DbSet<HelpMessage> HelpMessages { get; set; }
        public virtual DbSet<IntentCall> IntentCalls { get; set; }
        public virtual DbSet<IntentMessage> IntentMessages { get; set; }
        public virtual DbSet<IntentMessagesRead> IntentMessagesReads { get; set; }
        public virtual DbSet<Intent> Intents { get; set; }
        public virtual DbSet<RequestLog> RequestLogs { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<SkillType> SkillTypes { get; set; }
        public virtual DbSet<WelcomeMessage> WelcomeMessages { get; set; }
        public virtual DbSet<WelcomeMessagesRead> WelcomeMessagesReads { get; set; }
    }
}
