//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreTemperature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoreTemperature()
        {
            this.Meats = new HashSet<Meat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DefaultDegree { get; set; }
        public Nullable<int> DefaultMinDegree { get; set; }
        public Nullable<int> DefaultMaxDegree { get; set; }
        public Nullable<int> RareDegree { get; set; }
        public Nullable<int> RareMinDegree { get; set; }
        public Nullable<int> RareMaxDegree { get; set; }
        public Nullable<int> MediumDegree { get; set; }
        public Nullable<int> MediumMinDegree { get; set; }
        public Nullable<int> MediumMaxDegree { get; set; }
        public Nullable<int> DoneDegree { get; set; }
        public Nullable<int> DoneMinDegree { get; set; }
        public Nullable<int> DoneMaxDegree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meat> Meats { get; set; }
    }
}
