//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntentMessage()
        {
            this.IntentMessagesReads = new HashSet<IntentMessagesRead>();
        }
    
        public int Id { get; set; }
        public int IntentId { get; set; }
        public string Message { get; set; }
    
        public virtual Intent Intent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntentMessagesRead> IntentMessagesReads { get; set; }
    }
}
