//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meat
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CoreTemperatureId { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual CoreTemperature CoreTemperature { get; set; }
    }
}
