//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int Id { get; set; }
        public System.DateTime RequestTime { get; set; }
        public string ApplicationId { get; set; }
        public string UserId { get; set; }
        public string RequestType { get; set; }
        public string Intent { get; set; }
        public string IntentParam { get; set; }
        public string Information { get; set; }
    }
}
