//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.Skill.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchlistItem
    {
        public int Id { get; set; }
        public int AssetClassId { get; set; }
        public int CurrencyId { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsUsedForAlexaQuotes { get; set; }
        public bool IsUsedForAlexaNews { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Name { get; set; }
        public decimal Last { get; set; }
        public System.DateTime LastDate { get; set; }
        public decimal ChangeAbsolute { get; set; }
        public decimal ChangePercent { get; set; }
        public decimal DailyHigh { get; set; }
        public decimal DailyLow { get; set; }
        public decimal YearHigh { get; set; }
        public decimal YearLow { get; set; }
    
        public virtual AssetClass AssetClass { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
